---
Name: Voke Brume
Assignment: A6
Date: 03/24/2021
output:
  html_document:
    df_print: paged
  rmdformats::readthedown:
    self_contained: yes
    thumbnails: yes
    lightbox: yes
    gallery: yes
    highlight: tango
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tmap)
library(tmaptools)
library(rgdal)
library(sf)
library(raster)
indiana <- st_read("Indiana.shp")
wv_counties <- st_read("wv_counties.shp")
towns <- st_read("towns.shp")
interstates <- st_read("interstates.shp")
rivers <- st_read("rivers.shp")
dem <- raster("lc4.img")
ny_counties <- st_read("ny_counties.shp")
```


# Assignment 4
#### by Voke Brume


##### Map 1: Indiana Voting Result Map
```{r a, echo = TRUE, comment = "", colapse = TRUE}
tm_shape(indiana) +
tm_polygons(col = "winner12", title = "Political Parties", labels = c("Democrat", "republican"), style = "cat", palette = c("blue", "red")) +
tm_compass(position = c(.78,.09)) +
tm_scale_bar(position = c(.64,.03)) +
tm_layout(title = "Election Results", legend.outside = TRUE, legend.position = c("left", "top")) +
tm_credits("Data from US Census", position = c(.55,.00)) 
```



##### Map 2: Indiana Medium Income Map
```{r b, echo = TRUE, comment = "", colapse = TRUE}
tm_shape(indiana) +
tm_polygons(col = "med_income", title = "Income ($)", style = "cont", palette = get_brewer_pal(palette = "RdYlGn")) +
tm_compass(position = c(.78,.09)) +
tm_scale_bar(position = c(.64,.03)) +
tm_layout(title = "Median Income", legend.outside = TRUE, legend.position = c("left", "top")) +
tm_credits("Data from US Census", position = c(.55,.00))
```



##### Map 3: WV Population Data Map
```{r c, echo = TRUE, comment = "", colapse = TRUE}
tm_shape(wv_counties) +
tm_polygons(col = "POP2000", title = "Population in 2000", style = "cont", palette = get_brewer_pal(palette = "YlGn", n = 4)) +
tm_shape(interstates) +
tm_lines(col = "red", lwd = 2) +
tm_shape(rivers) +
tm_lines(col = "blue", lwd = 1.5) +
tm_shape(towns) +
tm_bubbles(size = "POPULATION", title.size = "Population of Towns")+
tm_compass(position = c("right", "bottom")) +
tm_scale_bar(position = c("right", "bottom")) +
tm_layout(title = "WV Population Data", legend.outside = TRUE, legend.position = c("left", "top"))
```



##### Map 4: Land Cover Map
```{r d, echo = TRUE, comment = "", colapse = TRUE}
tm_shape(dem) +
tm_raster(style = "cat", title = "Land Cover", labels = c("Water", "Developed", "Forest", "Other"), palette = c("deepskyblue", "brown", "darkolivegreen", "goldenrod3")) + 
tm_layout(legend.outside = TRUE) +
tm_shape(ny_counties) +
tm_borders(col = "black", lwd = 2) +
tm_compass(position = c(.89,.07)) +
tm_scale_bar(position = c(.68,.00)) +
tm_layout(title = "NY Land Cover", legend.outside = TRUE, legend.position = c("left", "top")) +
tm_credits("Data from NLCD", position = c(.00,.00))
```